services:
  - postgresql

stages:
  - installation
  - test
  # - coverage

cache:
  bundler: true
  directories:
    - ./client/node_modules

env:
  global:
    CC_TEST_REPORTER_ID=e187186042e95968f0b6d9c501f42c477d1025666bd6aef6d296c05df95eed4c

# before_install:
#   - cd api
#   - gem install bundler:2.1.4
#   - cd ..

jobs:
  include:
    - stage: installation
      name: "API Installation"
      language: ruby
      rvm:
        - 2.5.7
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - cd api
        - gem install bundler:2.1.4
      script:
        - bundle install
        - rake db:create
        - rake db:migrate
    - name: "Client Installation"
      language: node_js
      node_js: 14
      before_script:
        - cd client
      script:
        - yarn install

    # - stage: "Tests"
    #   script:
    #     - cd api
    #     - bundle exec rails test
      
    #   script:
    #     - cd client
    #     - yarn run test:unit


# jobs:
#   include:
#     - language: ruby
#       rvm:
#         - 2.5.7
#       before_install:
#         - cd api
#         - gem install bundler:2.1.4
#       install:
#         - bundle install
#       before_script:
#         - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#         - chmod +x ./cc-test-reporter
#         - rake db:create
#         - rake db:migrate
#       script:
#         - bundle exec rails test
#       after_script:
#         - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json ./coverage/.resultset.json # Format coverage
#         - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json

#     - language: node_js
#       node_js: 14
#       before_install:
#         - cd client
#       install:
#         - yarn install
#       script:
#         - yarn run test:unit
#       after_script:
