version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gces_user
      POSTGRES_PASSWORD: gces_rasa

  api:
    build: ./api
    restart: always
    depends_on:
      - db
    volumes:
      - ./api:/usr/api
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_USER: gces_user
      DB_PASSWORD: gces_rasa

  front:
    build: ./client
    restart: always
    volumes:
      - ./client/src:/usr/client/src
      - ./client/tests:/usr/client/tests
    ports:
      - 8080:8080
